/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Version = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Tag = IDL.Record({ 'tagName' : IDL.Text });
export const Status = IDL.Variant({
  'ok' : IDL.Null,
  'expiringSoon' : IDL.Null,
  'expired' : IDL.Null,
});
export const Component = IDL.Record({
  'status' : Status,
  'validityDate' : IDL.Text,
  'expirationDate' : IDL.Text,
  'associatedBenchId' : IDL.Text,
  'manufacturerReference' : IDL.Text,
  'componentName' : IDL.Text,
});
export const Document = IDL.Record({
  'id' : IDL.Text,
  'documentVersion' : IDL.Opt(IDL.Text),
  'tags' : IDL.Vec(Tag),
  'version' : Version,
  'associatedBenches' : IDL.Vec(IDL.Text),
  'category' : IDL.Text,
  'uploader' : IDL.Principal,
  'productDisplayName' : IDL.Text,
  'semanticVersion' : IDL.Text,
  'fileReference' : ExternalBlob,
});
export const TestBench = IDL.Record({
  'id' : IDL.Text,
  'plmAgileUrl' : IDL.Text,
  'creator' : IDL.Opt(IDL.Principal),
  'documents' : IDL.Vec(IDL.Tuple(IDL.Text, Version)),
  'decawebUrl' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(Tag),
  'description' : IDL.Text,
  'photoUrl' : IDL.Opt(IDL.Text),
  'agileCode' : IDL.Text,
  'serialNumber' : IDL.Text,
  'photo' : ExternalBlob,
});
export const Time = IDL.Int;
export const HistoryEntry = IDL.Record({
  'action' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'details' : IDL.Text,
});
export const ExpirationThresholdMode = IDL.Variant({
  'allBenches' : IDL.Null,
  'customizedBenches' : IDL.Null,
});
export const ProfilePicture = IDL.Variant({
  'custom' : ExternalBlob,
  'avatar' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'entity' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'languageTag' : IDL.Text,
  'thresholdCustomizedBenches' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'avatarUrl' : IDL.Text,
  'thresholdAllBenches' : IDL.Nat,
  'expirationThresholdMode' : ExpirationThresholdMode,
  'profilePicture' : ProfilePicture,
  'lastSeen' : IDL.Opt(IDL.Int),
  'dashboardSectionsOrdered' : IDL.Vec(IDL.Text),
});
export const PublicUserInfo = IDL.Record({
  'name' : IDL.Text,
  'profilePicture' : ProfilePicture,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'associateDocumentToBench' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createDocument' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Version,
        IDL.Text,
        ExternalBlob,
        IDL.Text,
        IDL.Vec(Tag),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'createTestBench' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(IDL.Text),
        IDL.Vec(Tag),
      ],
      [],
      [],
    ),
  'documentExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'duplicateComponentToBench' : IDL.Func(
      [IDL.Text, Component, IDL.Text],
      [],
      [],
    ),
  'duplicateComponentToBenches' : IDL.Func(
      [Component, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'filterDocumentsByTags' : IDL.Func(
      [IDL.Vec(Tag)],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'findExpiringDocuments' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(Document)],
      ['query'],
    ),
  'getAllEntities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllTestBenches' : IDL.Func([], [IDL.Vec(TestBench)], ['query']),
  'getAllowedEmailDomain' : IDL.Func([], [IDL.Text], ['query']),
  'getBenchHistory' : IDL.Func([IDL.Text], [IDL.Vec(HistoryEntry)], ['query']),
  'getBenchName' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getComponents' : IDL.Func([IDL.Text], [IDL.Vec(Component)], ['query']),
  'getLanguageTag' : IDL.Func([], [IDL.Text], ['query']),
  'getProfilePicture' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(ProfilePicture)],
      ['query'],
    ),
  'getPublicUserInfo' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(PublicUserInfo)],
      ['query'],
    ),
  'getTestBench' : IDL.Func([IDL.Text], [IDL.Opt(TestBench)], ['query']),
  'getUniqueEntities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsersByEntity' : IDL.Func([IDL.Text], [IDL.Vec(UserProfile)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOnline' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'removeDocumentFromBench' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeTestBench' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setAllowedEmailDomain' : IDL.Func([IDL.Text], [], []),
  'setComponents' : IDL.Func([IDL.Text, IDL.Vec(Component)], [], []),
  'setLanguageTag' : IDL.Func([IDL.Text], [], []),
  'setProfilePicture' : IDL.Func([ProfilePicture], [], []),
  'updateDashboardSectionsOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateExpirationPreferences' : IDL.Func(
      [ExpirationThresholdMode, IDL.Nat, IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      [],
      [],
    ),
  'updateLastSeen' : IDL.Func([], [], []),
  'updateTestBench' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Opt(IDL.Text),
        IDL.Vec(Tag),
      ],
      [],
      [],
    ),
  'uploadProfilePicture' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Version = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Tag = IDL.Record({ 'tagName' : IDL.Text });
  const Status = IDL.Variant({
    'ok' : IDL.Null,
    'expiringSoon' : IDL.Null,
    'expired' : IDL.Null,
  });
  const Component = IDL.Record({
    'status' : Status,
    'validityDate' : IDL.Text,
    'expirationDate' : IDL.Text,
    'associatedBenchId' : IDL.Text,
    'manufacturerReference' : IDL.Text,
    'componentName' : IDL.Text,
  });
  const Document = IDL.Record({
    'id' : IDL.Text,
    'documentVersion' : IDL.Opt(IDL.Text),
    'tags' : IDL.Vec(Tag),
    'version' : Version,
    'associatedBenches' : IDL.Vec(IDL.Text),
    'category' : IDL.Text,
    'uploader' : IDL.Principal,
    'productDisplayName' : IDL.Text,
    'semanticVersion' : IDL.Text,
    'fileReference' : ExternalBlob,
  });
  const TestBench = IDL.Record({
    'id' : IDL.Text,
    'plmAgileUrl' : IDL.Text,
    'creator' : IDL.Opt(IDL.Principal),
    'documents' : IDL.Vec(IDL.Tuple(IDL.Text, Version)),
    'decawebUrl' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(Tag),
    'description' : IDL.Text,
    'photoUrl' : IDL.Opt(IDL.Text),
    'agileCode' : IDL.Text,
    'serialNumber' : IDL.Text,
    'photo' : ExternalBlob,
  });
  const Time = IDL.Int;
  const HistoryEntry = IDL.Record({
    'action' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'details' : IDL.Text,
  });
  const ExpirationThresholdMode = IDL.Variant({
    'allBenches' : IDL.Null,
    'customizedBenches' : IDL.Null,
  });
  const ProfilePicture = IDL.Variant({
    'custom' : ExternalBlob,
    'avatar' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'entity' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'languageTag' : IDL.Text,
    'thresholdCustomizedBenches' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'avatarUrl' : IDL.Text,
    'thresholdAllBenches' : IDL.Nat,
    'expirationThresholdMode' : ExpirationThresholdMode,
    'profilePicture' : ProfilePicture,
    'lastSeen' : IDL.Opt(IDL.Int),
    'dashboardSectionsOrdered' : IDL.Vec(IDL.Text),
  });
  const PublicUserInfo = IDL.Record({
    'name' : IDL.Text,
    'profilePicture' : ProfilePicture,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'associateDocumentToBench' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createDocument' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Version,
          IDL.Text,
          ExternalBlob,
          IDL.Text,
          IDL.Vec(Tag),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'createTestBench' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Vec(Tag),
        ],
        [],
        [],
      ),
    'documentExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'duplicateComponentToBench' : IDL.Func(
        [IDL.Text, Component, IDL.Text],
        [],
        [],
      ),
    'duplicateComponentToBenches' : IDL.Func(
        [Component, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'filterDocumentsByTags' : IDL.Func(
        [IDL.Vec(Tag)],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'findExpiringDocuments' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(Document)],
        ['query'],
      ),
    'getAllEntities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllTestBenches' : IDL.Func([], [IDL.Vec(TestBench)], ['query']),
    'getAllowedEmailDomain' : IDL.Func([], [IDL.Text], ['query']),
    'getBenchHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HistoryEntry)],
        ['query'],
      ),
    'getBenchName' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getComponents' : IDL.Func([IDL.Text], [IDL.Vec(Component)], ['query']),
    'getLanguageTag' : IDL.Func([], [IDL.Text], ['query']),
    'getProfilePicture' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(ProfilePicture)],
        ['query'],
      ),
    'getPublicUserInfo' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(PublicUserInfo)],
        ['query'],
      ),
    'getTestBench' : IDL.Func([IDL.Text], [IDL.Opt(TestBench)], ['query']),
    'getUniqueEntities' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsersByEntity' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOnline' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'removeDocumentFromBench' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeTestBench' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setAllowedEmailDomain' : IDL.Func([IDL.Text], [], []),
    'setComponents' : IDL.Func([IDL.Text, IDL.Vec(Component)], [], []),
    'setLanguageTag' : IDL.Func([IDL.Text], [], []),
    'setProfilePicture' : IDL.Func([ProfilePicture], [], []),
    'updateDashboardSectionsOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateExpirationPreferences' : IDL.Func(
        [
          ExpirationThresholdMode,
          IDL.Nat,
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        ],
        [],
        [],
      ),
    'updateLastSeen' : IDL.Func([], [], []),
    'updateTestBench' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Opt(IDL.Text),
          IDL.Vec(Tag),
        ],
        [],
        [],
      ),
    'uploadProfilePicture' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };