/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Component {
  'status' : Status,
  'validityDate' : string,
  'expirationDate' : string,
  'associatedBenchId' : string,
  'manufacturerReference' : string,
  'componentName' : string,
}
export interface Document {
  'id' : string,
  'documentVersion' : [] | [string],
  'tags' : Array<Tag>,
  'version' : Version,
  'associatedBenches' : Array<string>,
  'category' : string,
  'uploader' : Principal,
  'productDisplayName' : string,
  'semanticVersion' : string,
  'fileReference' : ExternalBlob,
}
export type ExpirationThresholdMode = { 'allBenches' : null } |
  { 'customizedBenches' : null };
export type ExternalBlob = Uint8Array;
export interface HistoryEntry {
  'action' : string,
  'user' : Principal,
  'timestamp' : Time,
  'details' : string,
}
export type ProfilePicture = { 'custom' : ExternalBlob } |
  { 'avatar' : string };
export interface PublicUserInfo {
  'username' : string,
  'profilePicture' : ProfilePicture,
}
export type Status = { 'ok' : null } |
  { 'expiringSoon' : null } |
  { 'expired' : null };
export interface Tag { 'tagName' : string }
export interface TestBench {
  'id' : string,
  'plmAgileUrl' : string,
  'creator' : [] | [Principal],
  'documents' : Array<[string, Version]>,
  'decawebUrl' : string,
  'name' : string,
  'tags' : Array<Tag>,
  'description' : string,
  'photoUrl' : [] | [string],
  'agileCode' : string,
  'serialNumber' : string,
  'photo' : ExternalBlob,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'entity' : string,
  'username' : string,
  'languageTag' : string,
  'thresholdCustomizedBenches' : Array<[string, bigint]>,
  'userId' : string,
  'email' : string,
  'avatarUrl' : string,
  'thresholdAllBenches' : bigint,
  'expirationThresholdMode' : ExpirationThresholdMode,
  'profilePicture' : ProfilePicture,
  'lastSeen' : [] | [bigint],
  'dashboardSectionsOrdered' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Version = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'associateDocumentToBench' : ActorMethod<[string, string], undefined>,
  'createDocument' : ActorMethod<
    [
      string,
      string,
      Version,
      string,
      ExternalBlob,
      string,
      Array<Tag>,
      [] | [string],
    ],
    undefined
  >,
  'createTestBench' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      [] | [string],
      Array<Tag>,
    ],
    undefined
  >,
  'documentExists' : ActorMethod<[string], boolean>,
  'duplicateComponentToBench' : ActorMethod<
    [string, Component, string],
    undefined
  >,
  'duplicateComponentToBenches' : ActorMethod<
    [Component, Array<string>],
    undefined
  >,
  'filterDocumentsByTags' : ActorMethod<[Array<Tag>], Array<Document>>,
  'findExpiringDocuments' : ActorMethod<[[] | [bigint]], Array<Document>>,
  'getAllEntities' : ActorMethod<[], Array<string>>,
  'getAllTestBenches' : ActorMethod<[], Array<TestBench>>,
  'getAllowedEmailDomain' : ActorMethod<[], string>,
  'getBenchHistory' : ActorMethod<[string], Array<HistoryEntry>>,
  'getBenchName' : ActorMethod<[string], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getComponents' : ActorMethod<[string], Array<Component>>,
  'getLanguageTag' : ActorMethod<[], string>,
  'getProfilePicture' : ActorMethod<[Principal], [] | [ProfilePicture]>,
  'getPublicUserInfo' : ActorMethod<[Principal], [] | [PublicUserInfo]>,
  'getTestBench' : ActorMethod<[string], [] | [TestBench]>,
  'getUniqueEntities' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsersByEntity' : ActorMethod<[string], Array<UserProfile>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isOnline' : ActorMethod<[Principal], boolean>,
  'removeDocumentFromBench' : ActorMethod<[string, string], undefined>,
  'removeTestBench' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAllowedEmailDomain' : ActorMethod<[string], undefined>,
  'setComponents' : ActorMethod<[string, Array<Component>], undefined>,
  'setLanguageTag' : ActorMethod<[string], undefined>,
  'setProfilePicture' : ActorMethod<[ProfilePicture], undefined>,
  'updateDashboardSectionsOrder' : ActorMethod<[Array<string>], undefined>,
  'updateExpirationPreferences' : ActorMethod<
    [ExpirationThresholdMode, bigint, Array<[string, bigint]>],
    undefined
  >,
  'updateLastSeen' : ActorMethod<[], undefined>,
  'updateTestBench' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      ExternalBlob,
      [] | [string],
      Array<Tag>,
    ],
    undefined
  >,
  'uploadProfilePicture' : ActorMethod<[ExternalBlob], ExternalBlob>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];