/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface HistoryEntry {
    action: string;
    user: Principal;
    timestamp: Time;
    details: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Document {
    id: string;
    documentVersion?: string;
    tags: Array<Tag>;
    version: Version;
    associatedBenches: Array<string>;
    category: string;
    uploader: Principal;
    productDisplayName: string;
    semanticVersion: string;
    fileReference: ExternalBlob;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Component {
    status: Status;
    validityDate: string;
    expirationDate: string;
    componentName: string;
}
export type ProfilePicture = {
    __kind__: "custom";
    custom: ExternalBlob;
} | {
    __kind__: "avatar";
    avatar: string;
};
export interface TestBench {
    id: string;
    plmAgileUrl: string;
    creator?: Principal;
    documents: Array<[string, Version]>;
    name: string;
    tags: Array<Tag>;
    description: string;
    agileCode: string;
    photo: ExternalBlob;
}
export interface Tag {
    tagName: string;
}
export type Version = bigint;
export interface UserProfile {
    entity: string;
    thresholdCustomizedBenches: Array<[string, bigint]>;
    userId: string;
    name: string;
    email: string;
    thresholdAllBenches: bigint;
    expirationThresholdMode: ExpirationThresholdMode;
    profilePicture: ProfilePicture;
    lastSeen?: bigint;
    dashboardSectionsOrdered: Array<string>;
}
export enum ExpirationThresholdMode {
    allBenches = "allBenches",
    customizedBenches = "customizedBenches"
}
export enum Status {
    ok = "ok",
    expiringSoon = "expiringSoon",
    expired = "expired"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    associateDocumentToBench(documentId: string, benchId: string): Promise<void>;
    createDocument(id: string, productDisplayName: string, version: Version, category: string, fileReference: ExternalBlob, semanticVersion: string, tags: Array<Tag>, documentVersion: string | null): Promise<void>;
    createTestBench(id: string, name: string, agileCode: string, plmAgileUrl: string, description: string, photo: ExternalBlob, tags: Array<Tag>): Promise<void>;
    documentExists(documentId: string): Promise<boolean>;
    filterDocumentsByTags(tags: Array<Tag>): Promise<Array<Document>>;
    findExpiringDocuments(daysRemaining: bigint | null): Promise<Array<Document>>;
    getAllEntities(): Promise<Array<string>>;
    getAllTestBenches(): Promise<Array<TestBench>>;
    getAllowedEmailDomain(): Promise<string>;
    getBenchHistory(benchId: string): Promise<Array<HistoryEntry>>;
    getBenchName(benchId: string): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getComponents(benchId: string): Promise<Array<Component>>;
    getProfilePicture(userId: Principal): Promise<ProfilePicture | null>;
    getTestBench(benchId: string): Promise<TestBench | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsersByEntity(entity: string): Promise<Array<UserProfile>>;
    isCallerAdmin(): Promise<boolean>;
    isOnline(userId: Principal): Promise<boolean>;
    removeDocumentFromBench(documentId: string, benchId: string): Promise<void>;
    removeTestBench(benchId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setAllowedEmailDomain(newDomain: string): Promise<void>;
    setComponents(benchId: string, components: Array<Component>): Promise<void>;
    setProfilePicture(profilePicture: ProfilePicture): Promise<void>;
    updateDashboardSectionsOrder(sections: Array<string>): Promise<void>;
    updateExpirationPreferences(mode: ExpirationThresholdMode, thresholdAll: bigint, thresholdCustom: Array<[string, bigint]>): Promise<void>;
    updateLastSeen(): Promise<void>;
    updateTestBench(benchId: string, name: string, agileCode: string, plmAgileUrl: string, description: string, photo: ExternalBlob, tags: Array<Tag>): Promise<void>;
    uploadProfilePicture(picture: ExternalBlob): Promise<ExternalBlob>;
}
import type { Component as _Component, Document as _Document, ExpirationThresholdMode as _ExpirationThresholdMode, ExternalBlob as _ExternalBlob, ProfilePicture as _ProfilePicture, Status as _Status, Tag as _Tag, TestBench as _TestBench, UserProfile as _UserProfile, UserRole as _UserRole, Version as _Version, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async associateDocumentToBench(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.associateDocumentToBench(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.associateDocumentToBench(arg0, arg1);
            return result;
        }
    }
    async createDocument(arg0: string, arg1: string, arg2: Version, arg3: string, arg4: ExternalBlob, arg5: string, arg6: Array<Tag>, arg7: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createDocument(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDocument(arg0, arg1, arg2, arg3, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6, to_candid_opt_n11(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async createTestBench(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob, arg6: Array<Tag>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTestBench(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTestBench(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async documentExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.documentExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.documentExists(arg0);
            return result;
        }
    }
    async filterDocumentsByTags(arg0: Array<Tag>): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDocumentsByTags(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDocumentsByTags(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async findExpiringDocuments(arg0: bigint | null): Promise<Array<Document>> {
        if (this.processError) {
            try {
                const result = await this.actor.findExpiringDocuments(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findExpiringDocuments(to_candid_opt_n17(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEntities(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntities();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntities();
            return result;
        }
    }
    async getAllTestBenches(): Promise<Array<TestBench>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTestBenches();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTestBenches();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllowedEmailDomain(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllowedEmailDomain();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllowedEmailDomain();
            return result;
        }
    }
    async getBenchHistory(arg0: string): Promise<Array<HistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBenchHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBenchHistory(arg0);
            return result;
        }
    }
    async getBenchName(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getBenchName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBenchName(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComponents(arg0: string): Promise<Array<Component>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComponents(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComponents(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfilePicture(arg0: Principal): Promise<ProfilePicture | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfilePicture(arg0);
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfilePicture(arg0);
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTestBench(arg0: string): Promise<TestBench | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTestBench(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTestBench(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsersByEntity(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsersByEntity(arg0);
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsersByEntity(arg0);
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOnline(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOnline(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOnline(arg0);
            return result;
        }
    }
    async removeDocumentFromBench(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeDocumentFromBench(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeDocumentFromBench(arg0, arg1);
            return result;
        }
    }
    async removeTestBench(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeTestBench(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeTestBench(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setAllowedEmailDomain(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAllowedEmailDomain(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAllowedEmailDomain(arg0);
            return result;
        }
    }
    async setComponents(arg0: string, arg1: Array<Component>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setComponents(arg0, to_candid_vec_n46(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setComponents(arg0, to_candid_vec_n46(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async setProfilePicture(arg0: ProfilePicture): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProfilePicture(await to_candid_ProfilePicture_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProfilePicture(await to_candid_ProfilePicture_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateDashboardSectionsOrder(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDashboardSectionsOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDashboardSectionsOrder(arg0);
            return result;
        }
    }
    async updateExpirationPreferences(arg0: ExpirationThresholdMode, arg1: bigint, arg2: Array<[string, bigint]>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateExpirationPreferences(to_candid_ExpirationThresholdMode_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateExpirationPreferences(to_candid_ExpirationThresholdMode_n42(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async updateLastSeen(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLastSeen();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLastSeen();
            return result;
        }
    }
    async updateTestBench(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: ExternalBlob, arg6: Array<Tag>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTestBench(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5), arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTestBench(arg0, arg1, arg2, arg3, arg4, await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg5), arg6);
            return result;
        }
    }
    async uploadProfilePicture(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadProfilePicture(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadProfilePicture(await to_candid_ExternalBlob_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Component_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Component): Component {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_Document_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Document): Promise<Document> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ExpirationThresholdMode_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExpirationThresholdMode): ExpirationThresholdMode {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_ProfilePicture_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfilePicture): Promise<ProfilePicture> {
    return await from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_TestBench_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TestBench): Promise<TestBench> {
    return await from_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfilePicture]): Promise<ProfilePicture | null> {
    return value.length === 0 ? null : await from_candid_ProfilePicture_n27(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TestBench]): Promise<TestBench | null> {
    return value.length === 0 ? null : await from_candid_TestBench_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documentVersion: [] | [string];
    tags: Array<_Tag>;
    version: _Version;
    associatedBenches: Array<string>;
    category: string;
    uploader: Principal;
    productDisplayName: string;
    semanticVersion: string;
    fileReference: _ExternalBlob;
}): Promise<{
    id: string;
    documentVersion?: string;
    tags: Array<Tag>;
    version: Version;
    associatedBenches: Array<string>;
    category: string;
    uploader: Principal;
    productDisplayName: string;
    semanticVersion: string;
    fileReference: ExternalBlob;
}> {
    return {
        id: value.id,
        documentVersion: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.documentVersion)),
        tags: value.tags,
        version: value.version,
        associatedBenches: value.associatedBenches,
        category: value.category,
        uploader: value.uploader,
        productDisplayName: value.productDisplayName,
        semanticVersion: value.semanticVersion,
        fileReference: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.fileReference)
    };
}
async function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    plmAgileUrl: string;
    creator: [] | [Principal];
    documents: Array<[string, _Version]>;
    name: string;
    tags: Array<_Tag>;
    description: string;
    agileCode: string;
    photo: _ExternalBlob;
}): Promise<{
    id: string;
    plmAgileUrl: string;
    creator?: Principal;
    documents: Array<[string, Version]>;
    name: string;
    tags: Array<Tag>;
    description: string;
    agileCode: string;
    photo: ExternalBlob;
}> {
    return {
        id: value.id,
        plmAgileUrl: value.plmAgileUrl,
        creator: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.creator)),
        documents: value.documents,
        name: value.name,
        tags: value.tags,
        description: value.description,
        agileCode: value.agileCode,
        photo: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.photo)
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entity: string;
    thresholdCustomizedBenches: Array<[string, bigint]>;
    userId: string;
    name: string;
    email: string;
    thresholdAllBenches: bigint;
    expirationThresholdMode: _ExpirationThresholdMode;
    profilePicture: _ProfilePicture;
    lastSeen: [] | [bigint];
    dashboardSectionsOrdered: Array<string>;
}): Promise<{
    entity: string;
    thresholdCustomizedBenches: Array<[string, bigint]>;
    userId: string;
    name: string;
    email: string;
    thresholdAllBenches: bigint;
    expirationThresholdMode: ExpirationThresholdMode;
    profilePicture: ProfilePicture;
    lastSeen?: bigint;
    dashboardSectionsOrdered: Array<string>;
}> {
    return {
        entity: value.entity,
        thresholdCustomizedBenches: value.thresholdCustomizedBenches,
        userId: value.userId,
        name: value.name,
        email: value.email,
        thresholdAllBenches: value.thresholdAllBenches,
        expirationThresholdMode: from_candid_ExpirationThresholdMode_n25(_uploadFile, _downloadFile, value.expirationThresholdMode),
        profilePicture: await from_candid_ProfilePicture_n27(_uploadFile, _downloadFile, value.profilePicture),
        lastSeen: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.lastSeen)),
        dashboardSectionsOrdered: value.dashboardSectionsOrdered
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    validityDate: string;
    expirationDate: string;
    componentName: string;
}): {
    status: Status;
    validityDate: string;
    expirationDate: string;
    componentName: string;
} {
    return {
        status: from_candid_Status_n35(_uploadFile, _downloadFile, value.status),
        validityDate: value.validityDate,
        expirationDate: value.expirationDate,
        componentName: value.componentName
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    allBenches: null;
} | {
    customizedBenches: null;
}): ExpirationThresholdMode {
    return "allBenches" in value ? ExpirationThresholdMode.allBenches : "customizedBenches" in value ? ExpirationThresholdMode.customizedBenches : value;
}
async function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    custom: _ExternalBlob;
} | {
    avatar: string;
}): Promise<{
    __kind__: "custom";
    custom: ExternalBlob;
} | {
    __kind__: "avatar";
    avatar: string;
}> {
    return "custom" in value ? {
        __kind__: "custom",
        custom: await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value.custom)
    } : "avatar" in value ? {
        __kind__: "avatar",
        avatar: value.avatar
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    expiringSoon: null;
} | {
    expired: null;
}): Status {
    return "ok" in value ? Status.ok : "expiringSoon" in value ? Status.expiringSoon : "expired" in value ? Status.expired : value;
}
async function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Document>): Promise<Array<Document>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Document_n13(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TestBench>): Promise<Array<TestBench>> {
    return await Promise.all(value.map(async (x)=>await from_candid_TestBench_n19(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Component>): Array<Component> {
    return value.map((x)=>from_candid_Component_n33(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n23(_uploadFile, _downloadFile, x)));
}
function to_candid_Component_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Component): _Component {
    return to_candid_record_n48(_uploadFile, _downloadFile, value);
}
function to_candid_ExpirationThresholdMode_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpirationThresholdMode): _ExpirationThresholdMode {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_ProfilePicture_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfilePicture): Promise<_ProfilePicture> {
    return await to_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    entity: string;
    thresholdCustomizedBenches: Array<[string, bigint]>;
    userId: string;
    name: string;
    email: string;
    thresholdAllBenches: bigint;
    expirationThresholdMode: ExpirationThresholdMode;
    profilePicture: ProfilePicture;
    lastSeen?: bigint;
    dashboardSectionsOrdered: Array<string>;
}): Promise<{
    entity: string;
    thresholdCustomizedBenches: Array<[string, bigint]>;
    userId: string;
    name: string;
    email: string;
    thresholdAllBenches: bigint;
    expirationThresholdMode: _ExpirationThresholdMode;
    profilePicture: _ProfilePicture;
    lastSeen: [] | [bigint];
    dashboardSectionsOrdered: Array<string>;
}> {
    return {
        entity: value.entity,
        thresholdCustomizedBenches: value.thresholdCustomizedBenches,
        userId: value.userId,
        name: value.name,
        email: value.email,
        thresholdAllBenches: value.thresholdAllBenches,
        expirationThresholdMode: to_candid_ExpirationThresholdMode_n42(_uploadFile, _downloadFile, value.expirationThresholdMode),
        profilePicture: await to_candid_ProfilePicture_n44(_uploadFile, _downloadFile, value.profilePicture),
        lastSeen: value.lastSeen ? candid_some(value.lastSeen) : candid_none(),
        dashboardSectionsOrdered: value.dashboardSectionsOrdered
    };
}
function to_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    validityDate: string;
    expirationDate: string;
    componentName: string;
}): {
    status: _Status;
    validityDate: string;
    expirationDate: string;
    componentName: string;
} {
    return {
        status: to_candid_Status_n49(_uploadFile, _downloadFile, value.status),
        validityDate: value.validityDate,
        expirationDate: value.expirationDate,
        componentName: value.componentName
    };
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExpirationThresholdMode): {
    allBenches: null;
} | {
    customizedBenches: null;
} {
    return value == ExpirationThresholdMode.allBenches ? {
        allBenches: null
    } : value == ExpirationThresholdMode.customizedBenches ? {
        customizedBenches: null
    } : value;
}
async function to_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "custom";
    custom: ExternalBlob;
} | {
    __kind__: "avatar";
    avatar: string;
}): Promise<{
    custom: _ExternalBlob;
} | {
    avatar: string;
}> {
    return value.__kind__ === "custom" ? {
        custom: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.custom)
    } : value.__kind__ === "avatar" ? {
        avatar: value.avatar
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    ok: null;
} | {
    expiringSoon: null;
} | {
    expired: null;
} {
    return value == Status.ok ? {
        ok: null
    } : value == Status.expiringSoon ? {
        expiringSoon: null
    } : value == Status.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Component>): Array<_Component> {
    return value.map((x)=>to_candid_Component_n47(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
